language: ruby
rvm:
- 2.4
deploy:
  api_key:
    secure: mYWcfaCnEHCjIXWTNmI2aSs0bTAkOPwxhQKePQFPLn1AFxGOs4CkyyhcLeCA7+DHJVxU/O8N5hss2IAflYWiwnP4BWXSAeMM98gzOOV37cLO31aChY3oEacGFQC5yKucRWxURiApcft0Yu95fK1kG8Vloq2Mgcrhm0fSJl4rBh0T8bjo/kiaaoJzUVVzNpQ4WQd1qHixbPVVhCStheL3QR5aHJA1MQ/D5ln+k+Hyei4lWMXCQgHYP79HXa6b/vKqok1CPpTGe9E4XIr8dn1BJnsUrxZPz+sACsr4N/GJnA8uGlUvz1smPJtCda/c/C2bVkvaVDrkgCca15akMITEDJ09bPoWmVwHBpQuDyY+nR4h9QrteadYmRD+h5Bpll7Xzq57mIPa0KL60ls6m5BcYo9PjsI6ykFD5h8ixFdNdpDQNUEQQoXwy2hTxRySXX5ZXG14r8CslU3KSEfSLe4GyPVcX7iFqeo9k9saTUcBkm1lQkFwOsC+CiFq1xL45aRvOawq8q/d3maRvVRe7y6AlDHl83E4zl3D/C5bJQtvofZBJwwV93EsfCGRk5qcaDi6glhZqIf1Vdnre469di3grVxRfWKQkxoaG9tR6hkT02B2TcGq+2s8GaJ471tHfdqxefrTRWZiAVEm+Nj4DPx4c/tV3u74MQmuD05ojLi6lNo=
